
import React, { useState } from 'react';
import { Ticket, TicketStatus, TicketPriority, Reply } from '../types';
import { DBService } from '../services/dbService';

interface TicketDetailProps {
  ticket: Ticket;
  onRefresh: () => void;
}

const TicketDetail: React.FC<TicketDetailProps> = ({ ticket, onRefresh }) => {
  const [replyText, setReplyText] = useState('');

  const handleStatusChange = (newStatus: TicketStatus) => {
    const updatedTicket: Ticket = { 
      ...ticket, 
      status: newStatus,
      updatedAt: new Date().toISOString()
    };
    DBService.saveTicket(updatedTicket);
    onRefresh();
  };

  const handleSendReply = (msg: string, isAuto = false) => {
    if (!msg.trim()) return;

    const currentUser = DBService.getCurrentUser();
    if (!currentUser) return;

    const newReply: Reply = {
      id: Date.now().toString(),
      authorId: currentUser.id,
      authorName: currentUser.name,
      message: msg,
      createdAt: new Date().toISOString(),
      isAutoGenerated: isAuto
    };

    const updatedTicket: Ticket = {
      ...ticket,
      replies: [...ticket.replies, newReply],
      updatedAt: new Date().toISOString(),
      status: ticket.status === TicketStatus.OPEN ? TicketStatus.IN_PROGRESS : ticket.status
    };

    DBService.saveTicket(updatedTicket);
    setReplyText('');
    onRefresh();
  };

  const useAISuggestion = () => {
    if (ticket.aiAnalysis?.suggestedResponse) {
      setReplyText(ticket.aiAnalysis.suggestedResponse);
    }
  };

  const getPriorityColor = (p: TicketPriority) => {
    switch(p) {
      case TicketPriority.URGENT: return 'bg-red-500 text-white';
      case TicketPriority.HIGH: return 'bg-orange-500 text-white';
      case TicketPriority.MEDIUM: return 'bg-blue-500 text-white';
      case TicketPriority.LOW: return 'bg-slate-400 text-white';
    }
  };

  return (
    <div className="bg-white rounded-2xl border border-slate-200 h-[700px] flex flex-col shadow-sm overflow-hidden">
      {/* Header */}
      <div className="p-6 border-b border-slate-100 flex items-center justify-between bg-slate-50/50">
        <div className="flex items-center space-x-4">
          <div className={`w-3 h-3 rounded-full animate-pulse ${
            ticket.status === TicketStatus.OPEN ? 'bg-emerald-500' : 'bg-slate-300'
          }`}></div>
          <div>
            <h2 className="text-xl font-bold text-slate-800">{ticket.title}</h2>
            <p className="text-xs text-slate-500 flex items-center mt-0.5">
              Opened by <span className="font-semibold text-slate-700 ml-1">{ticket.userName}</span>
              <span className="mx-2">•</span>
              {new Date(ticket.createdAt).toLocaleString()}
            </p>
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <select 
            value={ticket.status} 
            onChange={(e) => handleStatusChange(e.target.value as TicketStatus)}
            className="text-xs font-semibold border border-slate-200 rounded-lg px-3 py-2 outline-none focus:ring-2 focus:ring-indigo-500"
          >
            {Object.values(TicketStatus).map(s => (
              <option key={s} value={s}>{s.replace('_', ' ')}</option>
            ))}
          </select>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto p-6 space-y-8 scrollbar-hide">
        {/* Original Issue */}
        <div className="flex space-x-4">
          <div className="w-10 h-10 rounded-full bg-slate-100 flex items-center justify-center shrink-0">
            <span className="text-slate-500 font-bold uppercase">{ticket.userName.charAt(0)}</span>
          </div>
          <div className="bg-slate-50 p-4 rounded-2xl rounded-tl-none border border-slate-100 flex-1">
            <p className="text-slate-800 whitespace-pre-wrap">{ticket.description}</p>
          </div>
        </div>

        {/* AI Insight Box */}
        {ticket.aiAnalysis && (
          <div className="bg-indigo-50/50 border border-indigo-100 rounded-2xl p-4">
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center space-x-2">
                <div className="p-1.5 bg-indigo-600 rounded-lg">
                  <svg className="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
                  </svg>
                </div>
                <span className="text-sm font-bold text-indigo-900">AI Intelligent Analysis</span>
              </div>
              <div className="flex items-center space-x-2">
                <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${getPriorityColor(ticket.aiAnalysis.priority)}`}>
                  {ticket.aiAnalysis.priority} PRIORITY
                </span>
                <span className="px-2 py-0.5 bg-white text-indigo-700 rounded text-[10px] font-bold border border-indigo-100">
                  {ticket.aiAnalysis.category}
                </span>
              </div>
            </div>
            <div className="grid grid-cols-3 gap-4 mb-4">
              <div className="bg-white p-3 rounded-xl border border-indigo-50">
                <div className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Sentiment</div>
                <div className="font-bold text-slate-700 mt-0.5">{ticket.aiAnalysis.sentiment}</div>
              </div>
              <div className="bg-white p-3 rounded-xl border border-indigo-50">
                <div className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Tone/Emotion</div>
                <div className="font-bold text-slate-700 mt-0.5 capitalize">{ticket.aiAnalysis.emotion}</div>
              </div>
              <div className="bg-white p-3 rounded-xl border border-indigo-50">
                <div className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Urgency</div>
                <div className="w-full bg-slate-100 h-1.5 rounded-full mt-2">
                  <div className="bg-indigo-600 h-full rounded-full" style={{ width: `${ticket.aiAnalysis.urgencyScore}%` }}></div>
                </div>
              </div>
            </div>
            {ticket.aiAnalysis.suggestedResponse && (
              <div className="bg-white/60 p-3 rounded-xl border border-indigo-50">
                <div className="flex items-center justify-between mb-1">
                  <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Suggested Reply</span>
                  <button onClick={useAISuggestion} className="text-[10px] text-indigo-600 font-bold hover:underline">Apply Template</button>
                </div>
                <p className="text-xs text-slate-600 line-clamp-3 italic">"{ticket.aiAnalysis.suggestedResponse}"</p>
              </div>
            )}
          </div>
        )}

        {/* Thread */}
        <div className="space-y-6">
          {ticket.replies.map(reply => (
            <div key={reply.id} className={`flex space-x-4 ${reply.isAutoGenerated ? 'opacity-80' : ''}`}>
              <div className={`w-10 h-10 rounded-full flex items-center justify-center shrink-0 ${
                reply.authorName === 'System Admin' ? 'bg-indigo-100 text-indigo-600' : 'bg-slate-100 text-slate-500'
              }`}>
                <span className="font-bold uppercase">{reply.authorName.charAt(0)}</span>
              </div>
              <div className="flex-1">
                <div className="flex items-baseline space-x-2 mb-1">
                  <span className="text-sm font-bold text-slate-800">{reply.authorName}</span>
                  <span className="text-[10px] text-slate-400">{new Date(reply.createdAt).toLocaleTimeString()}</span>
                </div>
                <div className="bg-white border border-slate-100 p-4 rounded-2xl rounded-tl-none shadow-sm">
                  <p className="text-slate-700 text-sm">{reply.message}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Footer / Reply Area */}
      <div className="p-4 bg-slate-50 border-t border-slate-200">
        <div className="relative">
          <textarea
            value={replyText}
            onChange={(e) => setReplyText(e.target.value)}
            className="w-full p-4 pr-16 border border-slate-200 rounded-2xl focus:ring-2 focus:ring-indigo-500 outline-none resize-none h-24 text-sm"
            placeholder="Type your response here..."
          />
          <button 
            onClick={() => handleSendReply(replyText)}
            className="absolute bottom-4 right-4 bg-indigo-600 text-white p-2 rounded-xl hover:bg-indigo-700 transition shadow-lg"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  );
};

export default TicketDetail;
