
export enum UserRole {
  USER = 'USER',
  ADMIN = 'ADMIN'
}

export enum TicketPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT'
}

export enum TicketStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  ESCALATED = 'ESCALATED'
}

export enum TicketCategory {
  DELIVERY_DELAY = 'Delivery Delay',
  RETURN_ISSUE = 'Return Issue',
  PAYMENT_PROBLEM = 'Payment Problem',
  TECHNICAL_ERROR = 'Technical Error',
  DAMAGED_PRODUCT = 'Damaged Product',
  OTHER = 'Other'
}

export interface User {
  id: string;
  email: string;
  name: string;
  role: UserRole;
  password?: string;
}

export interface TicketAIAnalysis {
  category: TicketCategory;
  priority: TicketPriority;
  sentiment: 'POSITIVE' | 'NEUTRAL' | 'NEGATIVE';
  emotion: string;
  urgencyScore: number; // 0 to 100
  suggestedResponse?: string;
}

export interface Ticket {
  id: string;
  userId: string;
  userName: string;
  title: string;
  description: string;
  status: TicketStatus;
  createdAt: string;
  updatedAt: string;
  aiAnalysis?: TicketAIAnalysis;
  replies: Reply[];
}

export interface Reply {
  id: string;
  authorId: string;
  authorName: string;
  message: string;
  createdAt: string;
  isAutoGenerated?: boolean;
}

export interface AppState {
  currentUser: User | null;
  tickets: Ticket[];
}
